workflows:
  android-qa-build:
    name: Android Build
    max_build_duration: 20
    instance_type: mac_mini_m2
    environment:
      node: v20.14.0
    scripts:
      - name: Install Dependencies
        script: |
          echo "✅ Listing root directory before install"
          ls -la
          echo "=== Installing Dependencies ==="
          echo "Running npm install..."
          npm install

          echo "✅ Listing root directory after install"
          ls -la
          echo "✅ Dependencies installed successfully"
          echo "node_modules count: $(ls node_modules | wc -l) packages"

      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
          echo "Android SDK location set"

      - name: Build Android release
        script: |
          cd android && ./gradlew assembleRelease && cd ../
